### ISSUE TITLE
 ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by gss214** [CVRL/OpenSourceIrisPAD#5]
Hello, I followed the steps in the readme but when I ran `filters.py` the following error occurred:

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
Traceback (most recent call last):
  File "filter.py", line 7, in <module>
    import bsif
ImportError: numpy.core.multiarray failed to import
```

I've tried to update numpy in several ways but the error persists. Would you help me?

**Comment by anasofia0** [comment]
I got the same problem, I think it might be related to the virtual env and the version on environment.yaml

**Comment by lucaspar** [comment]
I wasn't able to replicate this exact error, but I suspect this is due to an incompatible `bsif.so`. Thus I have removed the old `bsif.so` from the repo to avoid confusion. Please use the instructions in the readme to recreate a `bsif.so` that works on your machine.

If you have improvements, feel free to contribute by opening a pull request.
